blank_issues_enabled: false
contact_links:
  - name: DMCA Takedown Request
    url: https://nood.pictures/information/dmca
    about: You might have questions about using the DMCA process for copyrighted content.
