name: Deploy Project

on:
  push:
    branches: [master]

env:
  BASE_URL: "" # Match this to the base URL of your GitHub pages

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"
      - name: Install dependencies
        run: npm ci
      - name: Build project
        run: npm run build
      - name: Move files to docs/ directory
        run: mv ./dist ./docs
      - name: Commit files
        run: |
          git config --local user.name "GitHub Actions Bot"
          git add docs/
          git add -f literally-nosql.json
          git commit -m "Publish HTML (`date '+%F %T %Z'`)" -a
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: gh-pages
          force: true
